/**
 * zrok
 * zrok client access
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateFrontendRequest {
    'zId'?: string;
    'urlTemplate'?: string;
    'publicName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "zId",
            "baseName": "zId",
            "type": "string"
        },
        {
            "name": "urlTemplate",
            "baseName": "url_template",
            "type": "string"
        },
        {
            "name": "publicName",
            "baseName": "public_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateFrontendRequest.attributeTypeMap;
    }
}

