version: 2
updates:
  # bump the ziti CLI version that is built into the zrok CLI image
  - package-ecosystem: docker
    directory: "/docker/images/zrok"
    schedule:
      interval: weekly
    open-pull-requests-limit: 20
    groups:
      all:
        applies-to: version-updates
        update-types:
          - "major"
          - "minor"
          - "patch"

  # node, golang, openziti/ziti-cli in the compose build Dockerfile
  - package-ecosystem: docker
    directory: "/docker/compose/zrok2-instance"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      all:
        applies-to: version-updates
        update-types:
          - "major"
          - "minor"
          - "patch"

  # golang, debian in the cross-build container
  - package-ecosystem: docker
    directory: "/docker/images/cross-build"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      all:
        applies-to: version-updates
        update-types:
          - "major"
          - "minor"
          - "patch"
