version: 2
builds:
- main: ./cmd/zrok2
  binary: zrok2
  ldflags: "-s -w -X github.com/openziti/zrok/v2/build.Version={{.Tag}} -X github.com/openziti/zrok/v2/build.Hash={{.ShortCommit}}"
  env:
    - CGO_ENABLED=1
    - CC=/usr/bin/x86_64-w64-mingw32-gcc
  goos:
    - windows
  goarch:
    - amd64