version: 2
builds:
- id: zrok-armv8
  main: ./cmd/zrok2
  binary: zrok2
  ldflags: "-s -w -X github.com/openziti/zrok/v2/build.Version={{.Tag}} -X github.com/openziti/zrok/v2/build.Hash={{.ShortCommit}}"
  env:
    - CC=aarch64-linux-gnu-gcc
    - CGO_ENABLED=1
    - CC_FOR_TARGET=gcc-aarch64-linux-gnu
  goos:
    - linux
  goarch:
    - arm64
  goarm:
    - 8

nfpms:
  - package_name: zrok2
    id: zrok-cli
    vendor: NetFoundry
    homepage: https://zrok.io/
    maintainer: support@zrok.io
    description: |-
      zrok is a next-generation sharing platform, designed to make sharing network and file resources simple and
      secure.
    license: Apache 2.0

    # Build IDs for the builds you want to create NFPM packages for.
    ids:
      - zrok-armv8

    # Formats to be generated.
    formats:
      - deb
      - rpm

    # {{ .ConventionalFileName }} satisfies the RPM name convention.
    file_name_template: "{{ .ConventionalFileName }}"

    # Umask to be used on files without explicit mode set. (overridable)
    umask: 0o002

    # Package version within this release version.
    release: 1

    # Section.
    section: default

    # Priority.
    priority: optional

    # GoReleaser will automatically add the binaries here
    bindir: /usr/bin

    # Contents to add to the package.
    contents: []

  - package_name: zrok2-agent
    id: zrok-agent
    vendor: NetFoundry
    homepage: https://zrok.io/
    maintainer: support@zrok.io
    description: |
      This package provides zrok2-agent.service. Enable your zrok account on this device with "zrok2 enable". Run
      "systemctl enable --user --now zrok2-agent.service" to enable the service for the current user and visit the agent
      UI by running "zrok2 agent console".
    license: Apache 2.0

    # do not bundle the built binaries, only supporting files
    meta: true

    # Formats to be generated.
    formats:
      - deb
      - rpm

    # {{ .ConventionalFileName }} satisfies the RPM name convention.
    file_name_template: "{{ .ConventionalFileName }}"

    # Umask to be used on files without explicit mode set. (overridable)
    umask: 0o002

    # Package version within this release version.
    release: 1

    # Section.
    section: default

    # Priority.
    priority: optional

    # GoReleaser will automatically add the binaries here
    dependencies:
      - zrok2

    # this allows users to satisfy the requirement for jq another way, not with the package manager, e.g.
    # apt install --no-recommends zrok2-agent
    recommends: []

    overrides:
      # yum and dnf do not automatically install "weak deps" aka "recommends", so we need to add them as a dependency
      rpm:
        dependencies:
          - zrok2

    # Contents to add to the package.
    contents:
      - dst: /usr/lib/systemd/user/
        src: ./nfpm/zrok2-agent.service

      - dst: /usr/bin/zrok2-enable
        src: ./nfpm/zrok2-enable.bash
        file_info:
          mode: 0755

      - dst: /etc/zrok2/
        src: ./etc/caddy/multiple_upstream.Caddyfile
        type: config|noreplace
