/* tslint:disable */
/* eslint-disable */
/**
 * agent/agentGrpc/agent.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HttpShareHealthcheckResponse
 */
export interface HttpShareHealthcheckResponse {
    /**
     * 
     * @type {boolean}
     * @memberof HttpShareHealthcheckResponse
     */
    healthy?: boolean;
    /**
     * 
     * @type {string}
     * @memberof HttpShareHealthcheckResponse
     */
    error?: string;
}

/**
 * Check if a given object implements the HttpShareHealthcheckResponse interface.
 */
export function instanceOfHttpShareHealthcheckResponse(value: object): value is HttpShareHealthcheckResponse {
    return true;
}

export function HttpShareHealthcheckResponseFromJSON(json: any): HttpShareHealthcheckResponse {
    return HttpShareHealthcheckResponseFromJSONTyped(json, false);
}

export function HttpShareHealthcheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpShareHealthcheckResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'healthy': json['healthy'] == null ? undefined : json['healthy'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function HttpShareHealthcheckResponseToJSON(json: any): HttpShareHealthcheckResponse {
    return HttpShareHealthcheckResponseToJSONTyped(json, false);
}

export function HttpShareHealthcheckResponseToJSONTyped(value?: HttpShareHealthcheckResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'healthy': value['healthy'],
        'error': value['error'],
    };
}

