services:
  my-other-zrok-share:
    image: ${ZROK_CONTAINER_IMAGE:-docker.io/openziti/zrok}
    restart: unless-stopped
    entrypoint: zrok-share.bash
    depends_on:
      zrok-enable:
        condition: service_completed_successfully
    volumes:
      - zrok_env:/mnt
      - ./Caddyfile:/Caddyfile
    environment:
      # most relevant options
      ZROK_UNIQUE_NAME:     "my-other-zrok-share"
      ZROK_BACKEND_MODE:    caddy
      ZROK_TARGET:          /Caddyfile
      # internal configuration
      HOME: /mnt  # zrok homedir in container
