/* tslint:disable */
/* eslint-disable */
/**
 * zrok
 * zrok client access
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateNamespace201Response
 */
export interface CreateNamespace201Response {
    /**
     * 
     * @type {string}
     * @memberof CreateNamespace201Response
     */
    namespaceToken?: string;
}

/**
 * Check if a given object implements the CreateNamespace201Response interface.
 */
export function instanceOfCreateNamespace201Response(value: object): value is CreateNamespace201Response {
    return true;
}

export function CreateNamespace201ResponseFromJSON(json: any): CreateNamespace201Response {
    return CreateNamespace201ResponseFromJSONTyped(json, false);
}

export function CreateNamespace201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNamespace201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'namespaceToken': json['namespaceToken'] == null ? undefined : json['namespaceToken'],
    };
}

export function CreateNamespace201ResponseToJSON(json: any): CreateNamespace201Response {
    return CreateNamespace201ResponseToJSONTyped(json, false);
}

export function CreateNamespace201ResponseToJSONTyped(value?: CreateNamespace201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'namespaceToken': value['namespaceToken'],
    };
}

