/* tslint:disable */
/* eslint-disable */
/**
 * zrok
 * zrok client access
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnrollRequest
 */
export interface EnrollRequest {
    /**
     * 
     * @type {string}
     * @memberof EnrollRequest
     */
    envZId?: string;
}

/**
 * Check if a given object implements the EnrollRequest interface.
 */
export function instanceOfEnrollRequest(value: object): value is EnrollRequest {
    return true;
}

export function EnrollRequestFromJSON(json: any): EnrollRequest {
    return EnrollRequestFromJSONTyped(json, false);
}

export function EnrollRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnrollRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'envZId': json['envZId'] == null ? undefined : json['envZId'],
    };
}

export function EnrollRequestToJSON(json: any): EnrollRequest {
    return EnrollRequestToJSONTyped(json, false);
}

export function EnrollRequestToJSONTyped(value?: EnrollRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'envZId': value['envZId'],
    };
}

