/* tslint:disable */
/* eslint-disable */
/**
 * zrok
 * zrok client access
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListShareNamespaces200ResponseInner
 */
export interface ListShareNamespaces200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ListShareNamespaces200ResponseInner
     */
    namespaceToken?: string;
    /**
     * 
     * @type {string}
     * @memberof ListShareNamespaces200ResponseInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ListShareNamespaces200ResponseInner
     */
    description?: string;
}

/**
 * Check if a given object implements the ListShareNamespaces200ResponseInner interface.
 */
export function instanceOfListShareNamespaces200ResponseInner(value: object): value is ListShareNamespaces200ResponseInner {
    return true;
}

export function ListShareNamespaces200ResponseInnerFromJSON(json: any): ListShareNamespaces200ResponseInner {
    return ListShareNamespaces200ResponseInnerFromJSONTyped(json, false);
}

export function ListShareNamespaces200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListShareNamespaces200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'namespaceToken': json['namespaceToken'] == null ? undefined : json['namespaceToken'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ListShareNamespaces200ResponseInnerToJSON(json: any): ListShareNamespaces200ResponseInner {
    return ListShareNamespaces200ResponseInnerToJSONTyped(json, false);
}

export function ListShareNamespaces200ResponseInnerToJSONTyped(value?: ListShareNamespaces200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'namespaceToken': value['namespaceToken'],
        'name': value['name'],
        'description': value['description'],
    };
}

