/* tslint:disable */
/* eslint-disable */
/**
 * zrok
 * zrok client access
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemoteStatus200ResponseSharesInner
 */
export interface RemoteStatus200ResponseSharesInner {
    /**
     * 
     * @type {string}
     * @memberof RemoteStatus200ResponseSharesInner
     */
    token?: string;
    /**
     * 
     * @type {string}
     * @memberof RemoteStatus200ResponseSharesInner
     */
    shareMode?: string;
    /**
     * 
     * @type {string}
     * @memberof RemoteStatus200ResponseSharesInner
     */
    backendMode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RemoteStatus200ResponseSharesInner
     */
    reserved?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof RemoteStatus200ResponseSharesInner
     */
    frontendEndpoints?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RemoteStatus200ResponseSharesInner
     */
    backendEndpoint?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RemoteStatus200ResponseSharesInner
     */
    open?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RemoteStatus200ResponseSharesInner
     */
    status?: string;
}

/**
 * Check if a given object implements the RemoteStatus200ResponseSharesInner interface.
 */
export function instanceOfRemoteStatus200ResponseSharesInner(value: object): value is RemoteStatus200ResponseSharesInner {
    return true;
}

export function RemoteStatus200ResponseSharesInnerFromJSON(json: any): RemoteStatus200ResponseSharesInner {
    return RemoteStatus200ResponseSharesInnerFromJSONTyped(json, false);
}

export function RemoteStatus200ResponseSharesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoteStatus200ResponseSharesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
        'shareMode': json['shareMode'] == null ? undefined : json['shareMode'],
        'backendMode': json['backendMode'] == null ? undefined : json['backendMode'],
        'reserved': json['reserved'] == null ? undefined : json['reserved'],
        'frontendEndpoints': json['frontendEndpoints'] == null ? undefined : json['frontendEndpoints'],
        'backendEndpoint': json['backendEndpoint'] == null ? undefined : json['backendEndpoint'],
        'open': json['open'] == null ? undefined : json['open'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function RemoteStatus200ResponseSharesInnerToJSON(json: any): RemoteStatus200ResponseSharesInner {
    return RemoteStatus200ResponseSharesInnerToJSONTyped(json, false);
}

export function RemoteStatus200ResponseSharesInnerToJSONTyped(value?: RemoteStatus200ResponseSharesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'shareMode': value['shareMode'],
        'backendMode': value['backendMode'],
        'reserved': value['reserved'],
        'frontendEndpoints': value['frontendEndpoints'],
        'backendEndpoint': value['backendEndpoint'],
        'open': value['open'],
        'status': value['status'],
    };
}

