/* tslint:disable */
/* eslint-disable */
/**
 * zrok
 * zrok client access
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShareHttpHealthcheckRequest
 */
export interface ShareHttpHealthcheckRequest {
    /**
     * 
     * @type {string}
     * @memberof ShareHttpHealthcheckRequest
     */
    envZId?: string;
    /**
     * 
     * @type {string}
     * @memberof ShareHttpHealthcheckRequest
     */
    shareToken?: string;
    /**
     * 
     * @type {string}
     * @memberof ShareHttpHealthcheckRequest
     */
    httpVerb?: string;
    /**
     * 
     * @type {string}
     * @memberof ShareHttpHealthcheckRequest
     */
    endpoint?: string;
    /**
     * 
     * @type {number}
     * @memberof ShareHttpHealthcheckRequest
     */
    expectedHttpResponse?: number;
    /**
     * 
     * @type {number}
     * @memberof ShareHttpHealthcheckRequest
     */
    timeoutMs?: number;
}

/**
 * Check if a given object implements the ShareHttpHealthcheckRequest interface.
 */
export function instanceOfShareHttpHealthcheckRequest(value: object): value is ShareHttpHealthcheckRequest {
    return true;
}

export function ShareHttpHealthcheckRequestFromJSON(json: any): ShareHttpHealthcheckRequest {
    return ShareHttpHealthcheckRequestFromJSONTyped(json, false);
}

export function ShareHttpHealthcheckRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareHttpHealthcheckRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'envZId': json['envZId'] == null ? undefined : json['envZId'],
        'shareToken': json['shareToken'] == null ? undefined : json['shareToken'],
        'httpVerb': json['httpVerb'] == null ? undefined : json['httpVerb'],
        'endpoint': json['endpoint'] == null ? undefined : json['endpoint'],
        'expectedHttpResponse': json['expectedHttpResponse'] == null ? undefined : json['expectedHttpResponse'],
        'timeoutMs': json['timeoutMs'] == null ? undefined : json['timeoutMs'],
    };
}

export function ShareHttpHealthcheckRequestToJSON(json: any): ShareHttpHealthcheckRequest {
    return ShareHttpHealthcheckRequestToJSONTyped(json, false);
}

export function ShareHttpHealthcheckRequestToJSONTyped(value?: ShareHttpHealthcheckRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'envZId': value['envZId'],
        'shareToken': value['shareToken'],
        'httpVerb': value['httpVerb'],
        'endpoint': value['endpoint'],
        'expectedHttpResponse': value['expectedHttpResponse'],
        'timeoutMs': value['timeoutMs'],
    };
}

