/* tslint:disable */
/* eslint-disable */
/**
 * zrok
 * zrok client access
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyResponse
 */
export interface VerifyResponse {
    /**
     * 
     * @type {string}
     * @memberof VerifyResponse
     */
    email?: string;
}

/**
 * Check if a given object implements the VerifyResponse interface.
 */
export function instanceOfVerifyResponse(value: object): value is VerifyResponse {
    return true;
}

export function VerifyResponseFromJSON(json: any): VerifyResponse {
    return VerifyResponseFromJSONTyped(json, false);
}

export function VerifyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function VerifyResponseToJSON(value?: VerifyResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
    };
}

