/* tslint:disable */
/* eslint-disable */
/**
 * zrok
 * zrok client access
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VersionInventory200Response
 */
export interface VersionInventory200Response {
    /**
     * 
     * @type {string}
     * @memberof VersionInventory200Response
     */
    controllerVersion?: string;
}

/**
 * Check if a given object implements the VersionInventory200Response interface.
 */
export function instanceOfVersionInventory200Response(value: object): value is VersionInventory200Response {
    return true;
}

export function VersionInventory200ResponseFromJSON(json: any): VersionInventory200Response {
    return VersionInventory200ResponseFromJSONTyped(json, false);
}

export function VersionInventory200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionInventory200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'controllerVersion': json['controllerVersion'] == null ? undefined : json['controllerVersion'],
    };
}

export function VersionInventory200ResponseToJSON(value?: VersionInventory200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'controllerVersion': value['controllerVersion'],
    };
}

