// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteFrontendParams creates a new DeleteFrontendParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteFrontendParams() *DeleteFrontendParams {
	return &DeleteFrontendParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteFrontendParamsWithTimeout creates a new DeleteFrontendParams object
// with the ability to set a timeout on a request.
func NewDeleteFrontendParamsWithTimeout(timeout time.Duration) *DeleteFrontendParams {
	return &DeleteFrontendParams{
		timeout: timeout,
	}
}

// NewDeleteFrontendParamsWithContext creates a new DeleteFrontendParams object
// with the ability to set a context for a request.
func NewDeleteFrontendParamsWithContext(ctx context.Context) *DeleteFrontendParams {
	return &DeleteFrontendParams{
		Context: ctx,
	}
}

// NewDeleteFrontendParamsWithHTTPClient creates a new DeleteFrontendParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteFrontendParamsWithHTTPClient(client *http.Client) *DeleteFrontendParams {
	return &DeleteFrontendParams{
		HTTPClient: client,
	}
}

/*
DeleteFrontendParams contains all the parameters to send to the API endpoint

	for the delete frontend operation.

	Typically these are written to a http.Request.
*/
type DeleteFrontendParams struct {

	// Body.
	Body DeleteFrontendBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete frontend params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteFrontendParams) WithDefaults() *DeleteFrontendParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete frontend params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteFrontendParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete frontend params
func (o *DeleteFrontendParams) WithTimeout(timeout time.Duration) *DeleteFrontendParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete frontend params
func (o *DeleteFrontendParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete frontend params
func (o *DeleteFrontendParams) WithContext(ctx context.Context) *DeleteFrontendParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete frontend params
func (o *DeleteFrontendParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete frontend params
func (o *DeleteFrontendParams) WithHTTPClient(client *http.Client) *DeleteFrontendParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete frontend params
func (o *DeleteFrontendParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the delete frontend params
func (o *DeleteFrontendParams) WithBody(body DeleteFrontendBody) *DeleteFrontendParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete frontend params
func (o *DeleteFrontendParams) SetBody(body DeleteFrontendBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteFrontendParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
