// Code generated by go-swagger; DO NOT EDIT.

package admin

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetNameReader is a Reader for the GetName structure.
type GetNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetNameUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /name/{namespaceToken}/{name}] getName", response, response.Code())
	}
}

// NewGetNameOK creates a GetNameOK with default headers values
func NewGetNameOK() *GetNameOK {
	return &GetNameOK{}
}

/*
GetNameOK describes a response with status code 200, with default header values.

ok
*/
type GetNameOK struct {
	Payload *GetNameOKBody
}

// IsSuccess returns true when this get name o k response has a 2xx status code
func (o *GetNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get name o k response has a 3xx status code
func (o *GetNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get name o k response has a 4xx status code
func (o *GetNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get name o k response has a 5xx status code
func (o *GetNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get name o k response a status code equal to that given
func (o *GetNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get name o k response
func (o *GetNameOK) Code() int {
	return 200
}

func (o *GetNameOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /name/{namespaceToken}/{name}][%d] getNameOK %s", 200, payload)
}

func (o *GetNameOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /name/{namespaceToken}/{name}][%d] getNameOK %s", 200, payload)
}

func (o *GetNameOK) GetPayload() *GetNameOKBody {
	return o.Payload
}

func (o *GetNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetNameOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetNameUnauthorized creates a GetNameUnauthorized with default headers values
func NewGetNameUnauthorized() *GetNameUnauthorized {
	return &GetNameUnauthorized{}
}

/*
GetNameUnauthorized describes a response with status code 401, with default header values.

unauthorized
*/
type GetNameUnauthorized struct {
}

// IsSuccess returns true when this get name unauthorized response has a 2xx status code
func (o *GetNameUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get name unauthorized response has a 3xx status code
func (o *GetNameUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get name unauthorized response has a 4xx status code
func (o *GetNameUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get name unauthorized response has a 5xx status code
func (o *GetNameUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get name unauthorized response a status code equal to that given
func (o *GetNameUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get name unauthorized response
func (o *GetNameUnauthorized) Code() int {
	return 401
}

func (o *GetNameUnauthorized) Error() string {
	return fmt.Sprintf("[GET /name/{namespaceToken}/{name}][%d] getNameUnauthorized", 401)
}

func (o *GetNameUnauthorized) String() string {
	return fmt.Sprintf("[GET /name/{namespaceToken}/{name}][%d] getNameUnauthorized", 401)
}

func (o *GetNameUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetNameNotFound creates a GetNameNotFound with default headers values
func NewGetNameNotFound() *GetNameNotFound {
	return &GetNameNotFound{}
}

/*
GetNameNotFound describes a response with status code 404, with default header values.

not found
*/
type GetNameNotFound struct {
}

// IsSuccess returns true when this get name not found response has a 2xx status code
func (o *GetNameNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get name not found response has a 3xx status code
func (o *GetNameNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get name not found response has a 4xx status code
func (o *GetNameNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get name not found response has a 5xx status code
func (o *GetNameNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get name not found response a status code equal to that given
func (o *GetNameNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get name not found response
func (o *GetNameNotFound) Code() int {
	return 404
}

func (o *GetNameNotFound) Error() string {
	return fmt.Sprintf("[GET /name/{namespaceToken}/{name}][%d] getNameNotFound", 404)
}

func (o *GetNameNotFound) String() string {
	return fmt.Sprintf("[GET /name/{namespaceToken}/{name}][%d] getNameNotFound", 404)
}

func (o *GetNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetNameInternalServerError creates a GetNameInternalServerError with default headers values
func NewGetNameInternalServerError() *GetNameInternalServerError {
	return &GetNameInternalServerError{}
}

/*
GetNameInternalServerError describes a response with status code 500, with default header values.

internal server error
*/
type GetNameInternalServerError struct {
}

// IsSuccess returns true when this get name internal server error response has a 2xx status code
func (o *GetNameInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get name internal server error response has a 3xx status code
func (o *GetNameInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get name internal server error response has a 4xx status code
func (o *GetNameInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get name internal server error response has a 5xx status code
func (o *GetNameInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get name internal server error response a status code equal to that given
func (o *GetNameInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get name internal server error response
func (o *GetNameInternalServerError) Code() int {
	return 500
}

func (o *GetNameInternalServerError) Error() string {
	return fmt.Sprintf("[GET /name/{namespaceToken}/{name}][%d] getNameInternalServerError", 500)
}

func (o *GetNameInternalServerError) String() string {
	return fmt.Sprintf("[GET /name/{namespaceToken}/{name}][%d] getNameInternalServerError", 500)
}

func (o *GetNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
GetNameOKBody get name o k body
swagger:model GetNameOKBody
*/
type GetNameOKBody struct {

	// account email
	// Required: true
	AccountEmail *string `json:"accountEmail"`

	// created at
	// Required: true
	CreatedAt *int64 `json:"createdAt"`

	// name
	// Required: true
	Name *string `json:"name"`

	// namespace name
	// Required: true
	NamespaceName *string `json:"namespaceName"`

	// namespace token
	// Required: true
	NamespaceToken *string `json:"namespaceToken"`

	// reserved
	// Required: true
	Reserved *bool `json:"reserved"`

	// share token
	// Required: true
	ShareToken *string `json:"shareToken"`
}

// Validate validates this get name o k body
func (o *GetNameOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAccountEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateNamespaceName(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateNamespaceToken(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateReserved(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateShareToken(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetNameOKBody) validateAccountEmail(formats strfmt.Registry) error {

	if err := validate.Required("getNameOK"+"."+"accountEmail", "body", o.AccountEmail); err != nil {
		return err
	}

	return nil
}

func (o *GetNameOKBody) validateCreatedAt(formats strfmt.Registry) error {

	if err := validate.Required("getNameOK"+"."+"createdAt", "body", o.CreatedAt); err != nil {
		return err
	}

	return nil
}

func (o *GetNameOKBody) validateName(formats strfmt.Registry) error {

	if err := validate.Required("getNameOK"+"."+"name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

func (o *GetNameOKBody) validateNamespaceName(formats strfmt.Registry) error {

	if err := validate.Required("getNameOK"+"."+"namespaceName", "body", o.NamespaceName); err != nil {
		return err
	}

	return nil
}

func (o *GetNameOKBody) validateNamespaceToken(formats strfmt.Registry) error {

	if err := validate.Required("getNameOK"+"."+"namespaceToken", "body", o.NamespaceToken); err != nil {
		return err
	}

	return nil
}

func (o *GetNameOKBody) validateReserved(formats strfmt.Registry) error {

	if err := validate.Required("getNameOK"+"."+"reserved", "body", o.Reserved); err != nil {
		return err
	}

	return nil
}

func (o *GetNameOKBody) validateShareToken(formats strfmt.Registry) error {

	if err := validate.Required("getNameOK"+"."+"shareToken", "body", o.ShareToken); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get name o k body based on context it is used
func (o *GetNameOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetNameOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetNameOKBody) UnmarshalBinary(b []byte) error {
	var res GetNameOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
