// Code generated by go-swagger; DO NOT EDIT.

package admin

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGrantSkipInterstitialParams creates a new GrantSkipInterstitialParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGrantSkipInterstitialParams() *GrantSkipInterstitialParams {
	return &GrantSkipInterstitialParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGrantSkipInterstitialParamsWithTimeout creates a new GrantSkipInterstitialParams object
// with the ability to set a timeout on a request.
func NewGrantSkipInterstitialParamsWithTimeout(timeout time.Duration) *GrantSkipInterstitialParams {
	return &GrantSkipInterstitialParams{
		timeout: timeout,
	}
}

// NewGrantSkipInterstitialParamsWithContext creates a new GrantSkipInterstitialParams object
// with the ability to set a context for a request.
func NewGrantSkipInterstitialParamsWithContext(ctx context.Context) *GrantSkipInterstitialParams {
	return &GrantSkipInterstitialParams{
		Context: ctx,
	}
}

// NewGrantSkipInterstitialParamsWithHTTPClient creates a new GrantSkipInterstitialParams object
// with the ability to set a custom HTTPClient for a request.
func NewGrantSkipInterstitialParamsWithHTTPClient(client *http.Client) *GrantSkipInterstitialParams {
	return &GrantSkipInterstitialParams{
		HTTPClient: client,
	}
}

/*
GrantSkipInterstitialParams contains all the parameters to send to the API endpoint

	for the grant skip interstitial operation.

	Typically these are written to a http.Request.
*/
type GrantSkipInterstitialParams struct {

	// Body.
	Body GrantSkipInterstitialBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the grant skip interstitial params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GrantSkipInterstitialParams) WithDefaults() *GrantSkipInterstitialParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the grant skip interstitial params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GrantSkipInterstitialParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the grant skip interstitial params
func (o *GrantSkipInterstitialParams) WithTimeout(timeout time.Duration) *GrantSkipInterstitialParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the grant skip interstitial params
func (o *GrantSkipInterstitialParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the grant skip interstitial params
func (o *GrantSkipInterstitialParams) WithContext(ctx context.Context) *GrantSkipInterstitialParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the grant skip interstitial params
func (o *GrantSkipInterstitialParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the grant skip interstitial params
func (o *GrantSkipInterstitialParams) WithHTTPClient(client *http.Client) *GrantSkipInterstitialParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the grant skip interstitial params
func (o *GrantSkipInterstitialParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the grant skip interstitial params
func (o *GrantSkipInterstitialParams) WithBody(body GrantSkipInterstitialBody) *GrantSkipInterstitialParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the grant skip interstitial params
func (o *GrantSkipInterstitialParams) SetBody(body GrantSkipInterstitialBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GrantSkipInterstitialParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
