// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ListLimitClassesReader is a Reader for the ListLimitClasses structure.
type ListLimitClassesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListLimitClassesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewListLimitClassesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListLimitClassesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListLimitClassesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /limit-class/list] listLimitClasses", response, response.Code())
	}
}

// NewListLimitClassesOK creates a ListLimitClassesOK with default headers values
func NewListLimitClassesOK() *ListLimitClassesOK {
	return &ListLimitClassesOK{}
}

/*
ListLimitClassesOK describes a response with status code 200, with default header values.

limit classes
*/
type ListLimitClassesOK struct {
	Payload []*ListLimitClassesOKBodyItems0
}

// IsSuccess returns true when this list limit classes o k response has a 2xx status code
func (o *ListLimitClassesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list limit classes o k response has a 3xx status code
func (o *ListLimitClassesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list limit classes o k response has a 4xx status code
func (o *ListLimitClassesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list limit classes o k response has a 5xx status code
func (o *ListLimitClassesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list limit classes o k response a status code equal to that given
func (o *ListLimitClassesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list limit classes o k response
func (o *ListLimitClassesOK) Code() int {
	return 200
}

func (o *ListLimitClassesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /limit-class/list][%d] listLimitClassesOK %s", 200, payload)
}

func (o *ListLimitClassesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /limit-class/list][%d] listLimitClassesOK %s", 200, payload)
}

func (o *ListLimitClassesOK) GetPayload() []*ListLimitClassesOKBodyItems0 {
	return o.Payload
}

func (o *ListLimitClassesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewListLimitClassesUnauthorized creates a ListLimitClassesUnauthorized with default headers values
func NewListLimitClassesUnauthorized() *ListLimitClassesUnauthorized {
	return &ListLimitClassesUnauthorized{}
}

/*
ListLimitClassesUnauthorized describes a response with status code 401, with default header values.

unauthorized
*/
type ListLimitClassesUnauthorized struct {
}

// IsSuccess returns true when this list limit classes unauthorized response has a 2xx status code
func (o *ListLimitClassesUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list limit classes unauthorized response has a 3xx status code
func (o *ListLimitClassesUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list limit classes unauthorized response has a 4xx status code
func (o *ListLimitClassesUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this list limit classes unauthorized response has a 5xx status code
func (o *ListLimitClassesUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this list limit classes unauthorized response a status code equal to that given
func (o *ListLimitClassesUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the list limit classes unauthorized response
func (o *ListLimitClassesUnauthorized) Code() int {
	return 401
}

func (o *ListLimitClassesUnauthorized) Error() string {
	return fmt.Sprintf("[POST /limit-class/list][%d] listLimitClassesUnauthorized", 401)
}

func (o *ListLimitClassesUnauthorized) String() string {
	return fmt.Sprintf("[POST /limit-class/list][%d] listLimitClassesUnauthorized", 401)
}

func (o *ListLimitClassesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListLimitClassesInternalServerError creates a ListLimitClassesInternalServerError with default headers values
func NewListLimitClassesInternalServerError() *ListLimitClassesInternalServerError {
	return &ListLimitClassesInternalServerError{}
}

/*
ListLimitClassesInternalServerError describes a response with status code 500, with default header values.

internal server error
*/
type ListLimitClassesInternalServerError struct {
}

// IsSuccess returns true when this list limit classes internal server error response has a 2xx status code
func (o *ListLimitClassesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list limit classes internal server error response has a 3xx status code
func (o *ListLimitClassesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list limit classes internal server error response has a 4xx status code
func (o *ListLimitClassesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list limit classes internal server error response has a 5xx status code
func (o *ListLimitClassesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list limit classes internal server error response a status code equal to that given
func (o *ListLimitClassesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the list limit classes internal server error response
func (o *ListLimitClassesInternalServerError) Code() int {
	return 500
}

func (o *ListLimitClassesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /limit-class/list][%d] listLimitClassesInternalServerError", 500)
}

func (o *ListLimitClassesInternalServerError) String() string {
	return fmt.Sprintf("[POST /limit-class/list][%d] listLimitClassesInternalServerError", 500)
}

func (o *ListLimitClassesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
ListLimitClassesBody list limit classes body
swagger:model ListLimitClassesBody
*/
type ListLimitClassesBody struct {

	// label
	Label string `json:"label,omitempty"`
}

// Validate validates this list limit classes body
func (o *ListLimitClassesBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this list limit classes body based on context it is used
func (o *ListLimitClassesBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ListLimitClassesBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListLimitClassesBody) UnmarshalBinary(b []byte) error {
	var res ListLimitClassesBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
ListLimitClassesOKBodyItems0 list limit classes o k body items0
swagger:model ListLimitClassesOKBodyItems0
*/
type ListLimitClassesOKBodyItems0 struct {

	// backend mode
	BackendMode string `json:"backendMode,omitempty"`

	// created at
	CreatedAt int64 `json:"createdAt,omitempty"`

	// environments
	Environments int64 `json:"environments,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// label
	Label string `json:"label,omitempty"`

	// limit action
	LimitAction string `json:"limitAction,omitempty"`

	// period minutes
	PeriodMinutes int64 `json:"periodMinutes,omitempty"`

	// reserved shares
	ReservedShares int64 `json:"reservedShares,omitempty"`

	// rx bytes
	RxBytes int64 `json:"rxBytes,omitempty"`

	// share frontends
	ShareFrontends int64 `json:"shareFrontends,omitempty"`

	// shares
	Shares int64 `json:"shares,omitempty"`

	// total bytes
	TotalBytes int64 `json:"totalBytes,omitempty"`

	// tx bytes
	TxBytes int64 `json:"txBytes,omitempty"`

	// unique names
	UniqueNames int64 `json:"uniqueNames,omitempty"`

	// updated at
	UpdatedAt int64 `json:"updatedAt,omitempty"`
}

// Validate validates this list limit classes o k body items0
func (o *ListLimitClassesOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this list limit classes o k body items0 based on context it is used
func (o *ListLimitClassesOKBodyItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ListLimitClassesOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListLimitClassesOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res ListLimitClassesOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
