// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRemoveNamespaceGrantParams creates a new RemoveNamespaceGrantParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRemoveNamespaceGrantParams() *RemoveNamespaceGrantParams {
	return &RemoveNamespaceGrantParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveNamespaceGrantParamsWithTimeout creates a new RemoveNamespaceGrantParams object
// with the ability to set a timeout on a request.
func NewRemoveNamespaceGrantParamsWithTimeout(timeout time.Duration) *RemoveNamespaceGrantParams {
	return &RemoveNamespaceGrantParams{
		timeout: timeout,
	}
}

// NewRemoveNamespaceGrantParamsWithContext creates a new RemoveNamespaceGrantParams object
// with the ability to set a context for a request.
func NewRemoveNamespaceGrantParamsWithContext(ctx context.Context) *RemoveNamespaceGrantParams {
	return &RemoveNamespaceGrantParams{
		Context: ctx,
	}
}

// NewRemoveNamespaceGrantParamsWithHTTPClient creates a new RemoveNamespaceGrantParams object
// with the ability to set a custom HTTPClient for a request.
func NewRemoveNamespaceGrantParamsWithHTTPClient(client *http.Client) *RemoveNamespaceGrantParams {
	return &RemoveNamespaceGrantParams{
		HTTPClient: client,
	}
}

/*
RemoveNamespaceGrantParams contains all the parameters to send to the API endpoint

	for the remove namespace grant operation.

	Typically these are written to a http.Request.
*/
type RemoveNamespaceGrantParams struct {

	// Body.
	Body RemoveNamespaceGrantBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the remove namespace grant params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveNamespaceGrantParams) WithDefaults() *RemoveNamespaceGrantParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the remove namespace grant params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveNamespaceGrantParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the remove namespace grant params
func (o *RemoveNamespaceGrantParams) WithTimeout(timeout time.Duration) *RemoveNamespaceGrantParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove namespace grant params
func (o *RemoveNamespaceGrantParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove namespace grant params
func (o *RemoveNamespaceGrantParams) WithContext(ctx context.Context) *RemoveNamespaceGrantParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove namespace grant params
func (o *RemoveNamespaceGrantParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove namespace grant params
func (o *RemoveNamespaceGrantParams) WithHTTPClient(client *http.Client) *RemoveNamespaceGrantParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove namespace grant params
func (o *RemoveNamespaceGrantParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the remove namespace grant params
func (o *RemoveNamespaceGrantParams) WithBody(body RemoveNamespaceGrantBody) *RemoveNamespaceGrantParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the remove namespace grant params
func (o *RemoveNamespaceGrantParams) SetBody(body RemoveNamespaceGrantBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveNamespaceGrantParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
