// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RevokeSkipInterstitialReader is a Reader for the RevokeSkipInterstitial structure.
type RevokeSkipInterstitialReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RevokeSkipInterstitialReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewRevokeSkipInterstitialOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewRevokeSkipInterstitialUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRevokeSkipInterstitialNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRevokeSkipInterstitialInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /skip-interstitial-grant] revokeSkipInterstitial", response, response.Code())
	}
}

// NewRevokeSkipInterstitialOK creates a RevokeSkipInterstitialOK with default headers values
func NewRevokeSkipInterstitialOK() *RevokeSkipInterstitialOK {
	return &RevokeSkipInterstitialOK{}
}

/*
RevokeSkipInterstitialOK describes a response with status code 200, with default header values.

ok
*/
type RevokeSkipInterstitialOK struct {
}

// IsSuccess returns true when this revoke skip interstitial o k response has a 2xx status code
func (o *RevokeSkipInterstitialOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this revoke skip interstitial o k response has a 3xx status code
func (o *RevokeSkipInterstitialOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this revoke skip interstitial o k response has a 4xx status code
func (o *RevokeSkipInterstitialOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this revoke skip interstitial o k response has a 5xx status code
func (o *RevokeSkipInterstitialOK) IsServerError() bool {
	return false
}

// IsCode returns true when this revoke skip interstitial o k response a status code equal to that given
func (o *RevokeSkipInterstitialOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the revoke skip interstitial o k response
func (o *RevokeSkipInterstitialOK) Code() int {
	return 200
}

func (o *RevokeSkipInterstitialOK) Error() string {
	return fmt.Sprintf("[DELETE /skip-interstitial-grant][%d] revokeSkipInterstitialOK", 200)
}

func (o *RevokeSkipInterstitialOK) String() string {
	return fmt.Sprintf("[DELETE /skip-interstitial-grant][%d] revokeSkipInterstitialOK", 200)
}

func (o *RevokeSkipInterstitialOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRevokeSkipInterstitialUnauthorized creates a RevokeSkipInterstitialUnauthorized with default headers values
func NewRevokeSkipInterstitialUnauthorized() *RevokeSkipInterstitialUnauthorized {
	return &RevokeSkipInterstitialUnauthorized{}
}

/*
RevokeSkipInterstitialUnauthorized describes a response with status code 401, with default header values.

unauthorized
*/
type RevokeSkipInterstitialUnauthorized struct {
}

// IsSuccess returns true when this revoke skip interstitial unauthorized response has a 2xx status code
func (o *RevokeSkipInterstitialUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this revoke skip interstitial unauthorized response has a 3xx status code
func (o *RevokeSkipInterstitialUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this revoke skip interstitial unauthorized response has a 4xx status code
func (o *RevokeSkipInterstitialUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this revoke skip interstitial unauthorized response has a 5xx status code
func (o *RevokeSkipInterstitialUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this revoke skip interstitial unauthorized response a status code equal to that given
func (o *RevokeSkipInterstitialUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the revoke skip interstitial unauthorized response
func (o *RevokeSkipInterstitialUnauthorized) Code() int {
	return 401
}

func (o *RevokeSkipInterstitialUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /skip-interstitial-grant][%d] revokeSkipInterstitialUnauthorized", 401)
}

func (o *RevokeSkipInterstitialUnauthorized) String() string {
	return fmt.Sprintf("[DELETE /skip-interstitial-grant][%d] revokeSkipInterstitialUnauthorized", 401)
}

func (o *RevokeSkipInterstitialUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRevokeSkipInterstitialNotFound creates a RevokeSkipInterstitialNotFound with default headers values
func NewRevokeSkipInterstitialNotFound() *RevokeSkipInterstitialNotFound {
	return &RevokeSkipInterstitialNotFound{}
}

/*
RevokeSkipInterstitialNotFound describes a response with status code 404, with default header values.

account not found
*/
type RevokeSkipInterstitialNotFound struct {
}

// IsSuccess returns true when this revoke skip interstitial not found response has a 2xx status code
func (o *RevokeSkipInterstitialNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this revoke skip interstitial not found response has a 3xx status code
func (o *RevokeSkipInterstitialNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this revoke skip interstitial not found response has a 4xx status code
func (o *RevokeSkipInterstitialNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this revoke skip interstitial not found response has a 5xx status code
func (o *RevokeSkipInterstitialNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this revoke skip interstitial not found response a status code equal to that given
func (o *RevokeSkipInterstitialNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the revoke skip interstitial not found response
func (o *RevokeSkipInterstitialNotFound) Code() int {
	return 404
}

func (o *RevokeSkipInterstitialNotFound) Error() string {
	return fmt.Sprintf("[DELETE /skip-interstitial-grant][%d] revokeSkipInterstitialNotFound", 404)
}

func (o *RevokeSkipInterstitialNotFound) String() string {
	return fmt.Sprintf("[DELETE /skip-interstitial-grant][%d] revokeSkipInterstitialNotFound", 404)
}

func (o *RevokeSkipInterstitialNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRevokeSkipInterstitialInternalServerError creates a RevokeSkipInterstitialInternalServerError with default headers values
func NewRevokeSkipInterstitialInternalServerError() *RevokeSkipInterstitialInternalServerError {
	return &RevokeSkipInterstitialInternalServerError{}
}

/*
RevokeSkipInterstitialInternalServerError describes a response with status code 500, with default header values.

internal server error
*/
type RevokeSkipInterstitialInternalServerError struct {
}

// IsSuccess returns true when this revoke skip interstitial internal server error response has a 2xx status code
func (o *RevokeSkipInterstitialInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this revoke skip interstitial internal server error response has a 3xx status code
func (o *RevokeSkipInterstitialInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this revoke skip interstitial internal server error response has a 4xx status code
func (o *RevokeSkipInterstitialInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this revoke skip interstitial internal server error response has a 5xx status code
func (o *RevokeSkipInterstitialInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this revoke skip interstitial internal server error response a status code equal to that given
func (o *RevokeSkipInterstitialInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the revoke skip interstitial internal server error response
func (o *RevokeSkipInterstitialInternalServerError) Code() int {
	return 500
}

func (o *RevokeSkipInterstitialInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /skip-interstitial-grant][%d] revokeSkipInterstitialInternalServerError", 500)
}

func (o *RevokeSkipInterstitialInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /skip-interstitial-grant][%d] revokeSkipInterstitialInternalServerError", 500)
}

func (o *RevokeSkipInterstitialInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
RevokeSkipInterstitialBody revoke skip interstitial body
swagger:model RevokeSkipInterstitialBody
*/
type RevokeSkipInterstitialBody struct {

	// email
	Email string `json:"email,omitempty"`
}

// Validate validates this revoke skip interstitial body
func (o *RevokeSkipInterstitialBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this revoke skip interstitial body based on context it is used
func (o *RevokeSkipInterstitialBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *RevokeSkipInterstitialBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RevokeSkipInterstitialBody) UnmarshalBinary(b []byte) error {
	var res RevokeSkipInterstitialBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
