// Code generated by go-swagger; DO NOT EDIT.

package metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openziti-test-kitchen/zrok/rest_model_zrok"
)

// ListIdentitiesReader is a Reader for the ListIdentities structure.
type ListIdentitiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListIdentitiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListIdentitiesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewListIdentitiesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListIdentitiesOK creates a ListIdentitiesOK with default headers values
func NewListIdentitiesOK() *ListIdentitiesOK {
	return &ListIdentitiesOK{}
}

/* ListIdentitiesOK describes a response with status code 200, with default header values.

success
*/
type ListIdentitiesOK struct {
	Payload rest_model_zrok.Identities
}

func (o *ListIdentitiesOK) Error() string {
	return fmt.Sprintf("[GET /listIdentities][%d] listIdentitiesOK  %+v", 200, o.Payload)
}
func (o *ListIdentitiesOK) GetPayload() rest_model_zrok.Identities {
	return o.Payload
}

func (o *ListIdentitiesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListIdentitiesInternalServerError creates a ListIdentitiesInternalServerError with default headers values
func NewListIdentitiesInternalServerError() *ListIdentitiesInternalServerError {
	return &ListIdentitiesInternalServerError{}
}

/* ListIdentitiesInternalServerError describes a response with status code 500, with default header values.

internal server error
*/
type ListIdentitiesInternalServerError struct {
	Payload rest_model_zrok.ErrorMessage
}

func (o *ListIdentitiesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /listIdentities][%d] listIdentitiesInternalServerError  %+v", 500, o.Payload)
}
func (o *ListIdentitiesInternalServerError) GetPayload() rest_model_zrok.ErrorMessage {
	return o.Payload
}

func (o *ListIdentitiesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
