// Code generated by go-swagger; DO NOT EDIT.

package metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListSharesParams creates a new ListSharesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListSharesParams() *ListSharesParams {
	return &ListSharesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListSharesParamsWithTimeout creates a new ListSharesParams object
// with the ability to set a timeout on a request.
func NewListSharesParamsWithTimeout(timeout time.Duration) *ListSharesParams {
	return &ListSharesParams{
		timeout: timeout,
	}
}

// NewListSharesParamsWithContext creates a new ListSharesParams object
// with the ability to set a context for a request.
func NewListSharesParamsWithContext(ctx context.Context) *ListSharesParams {
	return &ListSharesParams{
		Context: ctx,
	}
}

// NewListSharesParamsWithHTTPClient creates a new ListSharesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListSharesParamsWithHTTPClient(client *http.Client) *ListSharesParams {
	return &ListSharesParams{
		HTTPClient: client,
	}
}

/*
ListSharesParams contains all the parameters to send to the API endpoint

	for the list shares operation.

	Typically these are written to a http.Request.
*/
type ListSharesParams struct {

	/* ActivityDuration.

	   duration for hasActivity filter (e.g., "24h", "7d", "30d"). default "24h", maximum "30d" (720h)
	*/
	ActivityDuration *string

	/* BackendMode.

	   filter by backend mode
	*/
	BackendMode *string

	/* CreatedAfter.

	   filter by created date (RFC3339 format)
	*/
	CreatedAfter *string

	/* CreatedBefore.

	   filter by created date (RFC3339 format)
	*/
	CreatedBefore *string

	/* EnvZID.

	   filter by environment ziti identity
	*/
	EnvZID *string

	/* HasActivity.

	   filter shares with recent activity
	*/
	HasActivity *bool

	/* PermissionMode.

	   filter by permission mode (open/closed)
	*/
	PermissionMode *string

	/* ShareMode.

	   filter by share mode (public/private)
	*/
	ShareMode *string

	/* ShareToken.

	   filter by share token (substring match)
	*/
	ShareToken *string

	/* Target.

	   filter by target (substring match)
	*/
	Target *string

	/* UpdatedAfter.

	   filter by updated date (RFC3339 format)
	*/
	UpdatedAfter *string

	/* UpdatedBefore.

	   filter by updated date (RFC3339 format)
	*/
	UpdatedBefore *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list shares params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListSharesParams) WithDefaults() *ListSharesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list shares params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListSharesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list shares params
func (o *ListSharesParams) WithTimeout(timeout time.Duration) *ListSharesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list shares params
func (o *ListSharesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list shares params
func (o *ListSharesParams) WithContext(ctx context.Context) *ListSharesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list shares params
func (o *ListSharesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list shares params
func (o *ListSharesParams) WithHTTPClient(client *http.Client) *ListSharesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list shares params
func (o *ListSharesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithActivityDuration adds the activityDuration to the list shares params
func (o *ListSharesParams) WithActivityDuration(activityDuration *string) *ListSharesParams {
	o.SetActivityDuration(activityDuration)
	return o
}

// SetActivityDuration adds the activityDuration to the list shares params
func (o *ListSharesParams) SetActivityDuration(activityDuration *string) {
	o.ActivityDuration = activityDuration
}

// WithBackendMode adds the backendMode to the list shares params
func (o *ListSharesParams) WithBackendMode(backendMode *string) *ListSharesParams {
	o.SetBackendMode(backendMode)
	return o
}

// SetBackendMode adds the backendMode to the list shares params
func (o *ListSharesParams) SetBackendMode(backendMode *string) {
	o.BackendMode = backendMode
}

// WithCreatedAfter adds the createdAfter to the list shares params
func (o *ListSharesParams) WithCreatedAfter(createdAfter *string) *ListSharesParams {
	o.SetCreatedAfter(createdAfter)
	return o
}

// SetCreatedAfter adds the createdAfter to the list shares params
func (o *ListSharesParams) SetCreatedAfter(createdAfter *string) {
	o.CreatedAfter = createdAfter
}

// WithCreatedBefore adds the createdBefore to the list shares params
func (o *ListSharesParams) WithCreatedBefore(createdBefore *string) *ListSharesParams {
	o.SetCreatedBefore(createdBefore)
	return o
}

// SetCreatedBefore adds the createdBefore to the list shares params
func (o *ListSharesParams) SetCreatedBefore(createdBefore *string) {
	o.CreatedBefore = createdBefore
}

// WithEnvZID adds the envZID to the list shares params
func (o *ListSharesParams) WithEnvZID(envZID *string) *ListSharesParams {
	o.SetEnvZID(envZID)
	return o
}

// SetEnvZID adds the envZId to the list shares params
func (o *ListSharesParams) SetEnvZID(envZID *string) {
	o.EnvZID = envZID
}

// WithHasActivity adds the hasActivity to the list shares params
func (o *ListSharesParams) WithHasActivity(hasActivity *bool) *ListSharesParams {
	o.SetHasActivity(hasActivity)
	return o
}

// SetHasActivity adds the hasActivity to the list shares params
func (o *ListSharesParams) SetHasActivity(hasActivity *bool) {
	o.HasActivity = hasActivity
}

// WithPermissionMode adds the permissionMode to the list shares params
func (o *ListSharesParams) WithPermissionMode(permissionMode *string) *ListSharesParams {
	o.SetPermissionMode(permissionMode)
	return o
}

// SetPermissionMode adds the permissionMode to the list shares params
func (o *ListSharesParams) SetPermissionMode(permissionMode *string) {
	o.PermissionMode = permissionMode
}

// WithShareMode adds the shareMode to the list shares params
func (o *ListSharesParams) WithShareMode(shareMode *string) *ListSharesParams {
	o.SetShareMode(shareMode)
	return o
}

// SetShareMode adds the shareMode to the list shares params
func (o *ListSharesParams) SetShareMode(shareMode *string) {
	o.ShareMode = shareMode
}

// WithShareToken adds the shareToken to the list shares params
func (o *ListSharesParams) WithShareToken(shareToken *string) *ListSharesParams {
	o.SetShareToken(shareToken)
	return o
}

// SetShareToken adds the shareToken to the list shares params
func (o *ListSharesParams) SetShareToken(shareToken *string) {
	o.ShareToken = shareToken
}

// WithTarget adds the target to the list shares params
func (o *ListSharesParams) WithTarget(target *string) *ListSharesParams {
	o.SetTarget(target)
	return o
}

// SetTarget adds the target to the list shares params
func (o *ListSharesParams) SetTarget(target *string) {
	o.Target = target
}

// WithUpdatedAfter adds the updatedAfter to the list shares params
func (o *ListSharesParams) WithUpdatedAfter(updatedAfter *string) *ListSharesParams {
	o.SetUpdatedAfter(updatedAfter)
	return o
}

// SetUpdatedAfter adds the updatedAfter to the list shares params
func (o *ListSharesParams) SetUpdatedAfter(updatedAfter *string) {
	o.UpdatedAfter = updatedAfter
}

// WithUpdatedBefore adds the updatedBefore to the list shares params
func (o *ListSharesParams) WithUpdatedBefore(updatedBefore *string) *ListSharesParams {
	o.SetUpdatedBefore(updatedBefore)
	return o
}

// SetUpdatedBefore adds the updatedBefore to the list shares params
func (o *ListSharesParams) SetUpdatedBefore(updatedBefore *string) {
	o.UpdatedBefore = updatedBefore
}

// WriteToRequest writes these params to a swagger request
func (o *ListSharesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ActivityDuration != nil {

		// query param activityDuration
		var qrActivityDuration string

		if o.ActivityDuration != nil {
			qrActivityDuration = *o.ActivityDuration
		}
		qActivityDuration := qrActivityDuration
		if qActivityDuration != "" {

			if err := r.SetQueryParam("activityDuration", qActivityDuration); err != nil {
				return err
			}
		}
	}

	if o.BackendMode != nil {

		// query param backendMode
		var qrBackendMode string

		if o.BackendMode != nil {
			qrBackendMode = *o.BackendMode
		}
		qBackendMode := qrBackendMode
		if qBackendMode != "" {

			if err := r.SetQueryParam("backendMode", qBackendMode); err != nil {
				return err
			}
		}
	}

	if o.CreatedAfter != nil {

		// query param createdAfter
		var qrCreatedAfter string

		if o.CreatedAfter != nil {
			qrCreatedAfter = *o.CreatedAfter
		}
		qCreatedAfter := qrCreatedAfter
		if qCreatedAfter != "" {

			if err := r.SetQueryParam("createdAfter", qCreatedAfter); err != nil {
				return err
			}
		}
	}

	if o.CreatedBefore != nil {

		// query param createdBefore
		var qrCreatedBefore string

		if o.CreatedBefore != nil {
			qrCreatedBefore = *o.CreatedBefore
		}
		qCreatedBefore := qrCreatedBefore
		if qCreatedBefore != "" {

			if err := r.SetQueryParam("createdBefore", qCreatedBefore); err != nil {
				return err
			}
		}
	}

	if o.EnvZID != nil {

		// query param envZId
		var qrEnvZID string

		if o.EnvZID != nil {
			qrEnvZID = *o.EnvZID
		}
		qEnvZID := qrEnvZID
		if qEnvZID != "" {

			if err := r.SetQueryParam("envZId", qEnvZID); err != nil {
				return err
			}
		}
	}

	if o.HasActivity != nil {

		// query param hasActivity
		var qrHasActivity bool

		if o.HasActivity != nil {
			qrHasActivity = *o.HasActivity
		}
		qHasActivity := swag.FormatBool(qrHasActivity)
		if qHasActivity != "" {

			if err := r.SetQueryParam("hasActivity", qHasActivity); err != nil {
				return err
			}
		}
	}

	if o.PermissionMode != nil {

		// query param permissionMode
		var qrPermissionMode string

		if o.PermissionMode != nil {
			qrPermissionMode = *o.PermissionMode
		}
		qPermissionMode := qrPermissionMode
		if qPermissionMode != "" {

			if err := r.SetQueryParam("permissionMode", qPermissionMode); err != nil {
				return err
			}
		}
	}

	if o.ShareMode != nil {

		// query param shareMode
		var qrShareMode string

		if o.ShareMode != nil {
			qrShareMode = *o.ShareMode
		}
		qShareMode := qrShareMode
		if qShareMode != "" {

			if err := r.SetQueryParam("shareMode", qShareMode); err != nil {
				return err
			}
		}
	}

	if o.ShareToken != nil {

		// query param shareToken
		var qrShareToken string

		if o.ShareToken != nil {
			qrShareToken = *o.ShareToken
		}
		qShareToken := qrShareToken
		if qShareToken != "" {

			if err := r.SetQueryParam("shareToken", qShareToken); err != nil {
				return err
			}
		}
	}

	if o.Target != nil {

		// query param target
		var qrTarget string

		if o.Target != nil {
			qrTarget = *o.Target
		}
		qTarget := qrTarget
		if qTarget != "" {

			if err := r.SetQueryParam("target", qTarget); err != nil {
				return err
			}
		}
	}

	if o.UpdatedAfter != nil {

		// query param updatedAfter
		var qrUpdatedAfter string

		if o.UpdatedAfter != nil {
			qrUpdatedAfter = *o.UpdatedAfter
		}
		qUpdatedAfter := qrUpdatedAfter
		if qUpdatedAfter != "" {

			if err := r.SetQueryParam("updatedAfter", qUpdatedAfter); err != nil {
				return err
			}
		}
	}

	if o.UpdatedBefore != nil {

		// query param updatedBefore
		var qrUpdatedBefore string

		if o.UpdatedBefore != nil {
			qrUpdatedBefore = *o.UpdatedBefore
		}
		qUpdatedBefore := qrUpdatedBefore
		if qUpdatedBefore != "" {

			if err := r.SetQueryParam("updatedBefore", qUpdatedBefore); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
