// Code generated by go-swagger; DO NOT EDIT.

package metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListPublicFrontendsForAccountParams creates a new ListPublicFrontendsForAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListPublicFrontendsForAccountParams() *ListPublicFrontendsForAccountParams {
	return &ListPublicFrontendsForAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListPublicFrontendsForAccountParamsWithTimeout creates a new ListPublicFrontendsForAccountParams object
// with the ability to set a timeout on a request.
func NewListPublicFrontendsForAccountParamsWithTimeout(timeout time.Duration) *ListPublicFrontendsForAccountParams {
	return &ListPublicFrontendsForAccountParams{
		timeout: timeout,
	}
}

// NewListPublicFrontendsForAccountParamsWithContext creates a new ListPublicFrontendsForAccountParams object
// with the ability to set a context for a request.
func NewListPublicFrontendsForAccountParamsWithContext(ctx context.Context) *ListPublicFrontendsForAccountParams {
	return &ListPublicFrontendsForAccountParams{
		Context: ctx,
	}
}

// NewListPublicFrontendsForAccountParamsWithHTTPClient creates a new ListPublicFrontendsForAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewListPublicFrontendsForAccountParamsWithHTTPClient(client *http.Client) *ListPublicFrontendsForAccountParams {
	return &ListPublicFrontendsForAccountParams{
		HTTPClient: client,
	}
}

/*
ListPublicFrontendsForAccountParams contains all the parameters to send to the API endpoint

	for the list public frontends for account operation.

	Typically these are written to a http.Request.
*/
type ListPublicFrontendsForAccountParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list public frontends for account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListPublicFrontendsForAccountParams) WithDefaults() *ListPublicFrontendsForAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list public frontends for account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListPublicFrontendsForAccountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list public frontends for account params
func (o *ListPublicFrontendsForAccountParams) WithTimeout(timeout time.Duration) *ListPublicFrontendsForAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list public frontends for account params
func (o *ListPublicFrontendsForAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list public frontends for account params
func (o *ListPublicFrontendsForAccountParams) WithContext(ctx context.Context) *ListPublicFrontendsForAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list public frontends for account params
func (o *ListPublicFrontendsForAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list public frontends for account params
func (o *ListPublicFrontendsForAccountParams) WithHTTPClient(client *http.Client) *ListPublicFrontendsForAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list public frontends for account params
func (o *ListPublicFrontendsForAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListPublicFrontendsForAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
