# coding: utf-8

"""
    zrok

    zrok client access

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zrok_api.models.remote_status200_response_shares_inner_failure import RemoteStatus200ResponseSharesInnerFailure

class TestRemoteStatus200ResponseSharesInnerFailure(unittest.TestCase):
    """RemoteStatus200ResponseSharesInnerFailure unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RemoteStatus200ResponseSharesInnerFailure:
        """Test RemoteStatus200ResponseSharesInnerFailure
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RemoteStatus200ResponseSharesInnerFailure`
        """
        model = RemoteStatus200ResponseSharesInnerFailure()
        if include_optional:
            return RemoteStatus200ResponseSharesInnerFailure(
                id = '',
                count = 56,
                last_error = '',
                next_retry = ''
            )
        else:
            return RemoteStatus200ResponseSharesInnerFailure(
        )
        """

    def testRemoteStatus200ResponseSharesInnerFailure(self):
        """Test RemoteStatus200ResponseSharesInnerFailure"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
