# coding: utf-8

"""
    zrok

    zrok client access

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zrok_api.models.list_namespaces200_response_inner import ListNamespaces200ResponseInner

class TestListNamespaces200ResponseInner(unittest.TestCase):
    """ListNamespaces200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListNamespaces200ResponseInner:
        """Test ListNamespaces200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListNamespaces200ResponseInner`
        """
        model = ListNamespaces200ResponseInner()
        if include_optional:
            return ListNamespaces200ResponseInner(
                namespace_token = '',
                name = '',
                description = '',
                open = True,
                created_at = 56,
                updated_at = 56
            )
        else:
            return ListNamespaces200ResponseInner(
        )
        """

    def testListNamespaces200ResponseInner(self):
        """Test ListNamespaces200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
