# coding: utf-8

"""
    zrok

    zrok client access

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zrok_api.models.auth_user import AuthUser

class TestAuthUser(unittest.TestCase):
    """AuthUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthUser:
        """Test AuthUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthUser`
        """
        model = AuthUser()
        if include_optional:
            return AuthUser(
                username = '',
                password = ''
            )
        else:
            return AuthUser(
        )
        """

    def testAuthUser(self):
        """Test AuthUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
