# coding: utf-8

"""
    zrok

    zrok client access

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zrok_api.models.remote_status200_response_accesses_inner import RemoteStatus200ResponseAccessesInner

class TestRemoteStatus200ResponseAccessesInner(unittest.TestCase):
    """RemoteStatus200ResponseAccessesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RemoteStatus200ResponseAccessesInner:
        """Test RemoteStatus200ResponseAccessesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RemoteStatus200ResponseAccessesInner`
        """
        model = RemoteStatus200ResponseAccessesInner()
        if include_optional:
            return RemoteStatus200ResponseAccessesInner(
                frontend_token = '',
                token = '',
                bind_address = '',
                response_headers = [
                    ''
                    ],
                status = '',
                failure = zrok_api.models.remote_status_200_response_shares_inner_failure.remoteStatus_200_response_shares_inner_failure(
                    id = '', 
                    count = 56, 
                    last_error = '', 
                    next_retry = '', )
            )
        else:
            return RemoteStatus200ResponseAccessesInner(
        )
        """

    def testRemoteStatus200ResponseAccessesInner(self):
        """Test RemoteStatus200ResponseAccessesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
