# coding: utf-8

"""
    zrok

    zrok client access

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zrok_api.models.apply_limit_classes_request import ApplyLimitClassesRequest

class TestApplyLimitClassesRequest(unittest.TestCase):
    """ApplyLimitClassesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplyLimitClassesRequest:
        """Test ApplyLimitClassesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApplyLimitClassesRequest`
        """
        model = ApplyLimitClassesRequest()
        if include_optional:
            return ApplyLimitClassesRequest(
                email = '',
                limit_class_ids = [
                    56
                    ]
            )
        else:
            return ApplyLimitClassesRequest(
        )
        """

    def testApplyLimitClassesRequest(self):
        """Test ApplyLimitClassesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
