# coding: utf-8

"""
    zrok

    zrok client access

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from zrok_api.models.list_namespace_frontend_mappings200_response_inner import ListNamespaceFrontendMappings200ResponseInner

class TestListNamespaceFrontendMappings200ResponseInner(unittest.TestCase):
    """ListNamespaceFrontendMappings200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListNamespaceFrontendMappings200ResponseInner:
        """Test ListNamespaceFrontendMappings200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListNamespaceFrontendMappings200ResponseInner`
        """
        model = ListNamespaceFrontendMappings200ResponseInner()
        if include_optional:
            return ListNamespaceFrontendMappings200ResponseInner(
                namespace_token = '',
                frontend_token = '',
                created_at = 56
            )
        else:
            return ListNamespaceFrontendMappings200ResponseInner(
        )
        """

    def testListNamespaceFrontendMappings200ResponseInner(self):
        """Test ListNamespaceFrontendMappings200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
