// Code generated by go-swagger; DO NOT EDIT.

package environment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openziti/zrok/rest_model_zrok"
)

// DisableHandlerFunc turns a function with the right signature into a disable handler
type DisableHandlerFunc func(DisableParams, *rest_model_zrok.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DisableHandlerFunc) Handle(params DisableParams, principal *rest_model_zrok.Principal) middleware.Responder {
	return fn(params, principal)
}

// DisableHandler interface for that can handle valid disable params
type DisableHandler interface {
	Handle(DisableParams, *rest_model_zrok.Principal) middleware.Responder
}

// NewDisable creates a new http.Handler for the disable operation
func NewDisable(ctx *middleware.Context, handler DisableHandler) *Disable {
	return &Disable{Context: ctx, Handler: handler}
}

/*
	Disable swagger:route POST /disable environment disable

Disable disable API
*/
type Disable struct {
	Context *middleware.Context
	Handler DisableHandler
}

func (o *Disable) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDisableParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *rest_model_zrok.Principal
	if uprinc != nil {
		principal = uprinc.(*rest_model_zrok.Principal) // this is really a rest_model_zrok.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
