// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openziti-test-kitchen/zrok/rest_model_zrok"
)

// ShareHandlerFunc turns a function with the right signature into a share handler
type ShareHandlerFunc func(ShareParams, *rest_model_zrok.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn ShareHandlerFunc) Handle(params ShareParams, principal *rest_model_zrok.Principal) middleware.Responder {
	return fn(params, principal)
}

// ShareHandler interface for that can handle valid share params
type ShareHandler interface {
	Handle(ShareParams, *rest_model_zrok.Principal) middleware.Responder
}

// NewShare creates a new http.Handler for the share operation
func NewShare(ctx *middleware.Context, handler ShareHandler) *Share {
	return &Share{Context: ctx, Handler: handler}
}

/*
	Share swagger:route POST /share service share

Share share API
*/
type Share struct {
	Context *middleware.Context
	Handler ShareHandler
}

func (o *Share) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewShareParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *rest_model_zrok.Principal
	if uprinc != nil {
		principal = uprinc.(*rest_model_zrok.Principal) // this is really a rest_model_zrok.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
