# coding: utf-8

"""
    zrok

    zrok client access  # noqa: E501

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdateFrontendRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'frontend_token': 'str',
        'public_name': 'str',
        'url_template': 'str'
    }

    attribute_map = {
        'frontend_token': 'frontendToken',
        'public_name': 'publicName',
        'url_template': 'urlTemplate'
    }

    def __init__(self, frontend_token=None, public_name=None, url_template=None):  # noqa: E501
        """UpdateFrontendRequest - a model defined in Swagger"""  # noqa: E501
        self._frontend_token = None
        self._public_name = None
        self._url_template = None
        self.discriminator = None
        if frontend_token is not None:
            self.frontend_token = frontend_token
        if public_name is not None:
            self.public_name = public_name
        if url_template is not None:
            self.url_template = url_template

    @property
    def frontend_token(self):
        """Gets the frontend_token of this UpdateFrontendRequest.  # noqa: E501


        :return: The frontend_token of this UpdateFrontendRequest.  # noqa: E501
        :rtype: str
        """
        return self._frontend_token

    @frontend_token.setter
    def frontend_token(self, frontend_token):
        """Sets the frontend_token of this UpdateFrontendRequest.


        :param frontend_token: The frontend_token of this UpdateFrontendRequest.  # noqa: E501
        :type: str
        """

        self._frontend_token = frontend_token

    @property
    def public_name(self):
        """Gets the public_name of this UpdateFrontendRequest.  # noqa: E501


        :return: The public_name of this UpdateFrontendRequest.  # noqa: E501
        :rtype: str
        """
        return self._public_name

    @public_name.setter
    def public_name(self, public_name):
        """Sets the public_name of this UpdateFrontendRequest.


        :param public_name: The public_name of this UpdateFrontendRequest.  # noqa: E501
        :type: str
        """

        self._public_name = public_name

    @property
    def url_template(self):
        """Gets the url_template of this UpdateFrontendRequest.  # noqa: E501


        :return: The url_template of this UpdateFrontendRequest.  # noqa: E501
        :rtype: str
        """
        return self._url_template

    @url_template.setter
    def url_template(self, url_template):
        """Sets the url_template of this UpdateFrontendRequest.


        :param url_template: The url_template of this UpdateFrontendRequest.  # noqa: E501
        :type: str
        """

        self._url_template = url_template

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateFrontendRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateFrontendRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
