// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MfaChallengeReader is a Reader for the MfaChallenge structure.
type MfaChallengeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MfaChallengeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewMfaChallengeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewMfaChallengeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewMfaChallengeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewMfaChallengeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /mfa/challenge] mfaChallenge", response, response.Code())
	}
}

// NewMfaChallengeOK creates a MfaChallengeOK with default headers values
func NewMfaChallengeOK() *MfaChallengeOK {
	return &MfaChallengeOK{}
}

/*
MfaChallengeOK describes a response with status code 200, with default header values.

challenge token issued
*/
type MfaChallengeOK struct {
	Payload *MfaChallengeOKBody
}

// IsSuccess returns true when this mfa challenge o k response has a 2xx status code
func (o *MfaChallengeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this mfa challenge o k response has a 3xx status code
func (o *MfaChallengeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this mfa challenge o k response has a 4xx status code
func (o *MfaChallengeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this mfa challenge o k response has a 5xx status code
func (o *MfaChallengeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this mfa challenge o k response a status code equal to that given
func (o *MfaChallengeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the mfa challenge o k response
func (o *MfaChallengeOK) Code() int {
	return 200
}

func (o *MfaChallengeOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /mfa/challenge][%d] mfaChallengeOK %s", 200, payload)
}

func (o *MfaChallengeOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /mfa/challenge][%d] mfaChallengeOK %s", 200, payload)
}

func (o *MfaChallengeOK) GetPayload() *MfaChallengeOKBody {
	return o.Payload
}

func (o *MfaChallengeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(MfaChallengeOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewMfaChallengeBadRequest creates a MfaChallengeBadRequest with default headers values
func NewMfaChallengeBadRequest() *MfaChallengeBadRequest {
	return &MfaChallengeBadRequest{}
}

/*
MfaChallengeBadRequest describes a response with status code 400, with default header values.

invalid code or mfa not enabled
*/
type MfaChallengeBadRequest struct {
}

// IsSuccess returns true when this mfa challenge bad request response has a 2xx status code
func (o *MfaChallengeBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this mfa challenge bad request response has a 3xx status code
func (o *MfaChallengeBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this mfa challenge bad request response has a 4xx status code
func (o *MfaChallengeBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this mfa challenge bad request response has a 5xx status code
func (o *MfaChallengeBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this mfa challenge bad request response a status code equal to that given
func (o *MfaChallengeBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the mfa challenge bad request response
func (o *MfaChallengeBadRequest) Code() int {
	return 400
}

func (o *MfaChallengeBadRequest) Error() string {
	return fmt.Sprintf("[POST /mfa/challenge][%d] mfaChallengeBadRequest", 400)
}

func (o *MfaChallengeBadRequest) String() string {
	return fmt.Sprintf("[POST /mfa/challenge][%d] mfaChallengeBadRequest", 400)
}

func (o *MfaChallengeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewMfaChallengeUnauthorized creates a MfaChallengeUnauthorized with default headers values
func NewMfaChallengeUnauthorized() *MfaChallengeUnauthorized {
	return &MfaChallengeUnauthorized{}
}

/*
MfaChallengeUnauthorized describes a response with status code 401, with default header values.

unauthorized
*/
type MfaChallengeUnauthorized struct {
}

// IsSuccess returns true when this mfa challenge unauthorized response has a 2xx status code
func (o *MfaChallengeUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this mfa challenge unauthorized response has a 3xx status code
func (o *MfaChallengeUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this mfa challenge unauthorized response has a 4xx status code
func (o *MfaChallengeUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this mfa challenge unauthorized response has a 5xx status code
func (o *MfaChallengeUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this mfa challenge unauthorized response a status code equal to that given
func (o *MfaChallengeUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the mfa challenge unauthorized response
func (o *MfaChallengeUnauthorized) Code() int {
	return 401
}

func (o *MfaChallengeUnauthorized) Error() string {
	return fmt.Sprintf("[POST /mfa/challenge][%d] mfaChallengeUnauthorized", 401)
}

func (o *MfaChallengeUnauthorized) String() string {
	return fmt.Sprintf("[POST /mfa/challenge][%d] mfaChallengeUnauthorized", 401)
}

func (o *MfaChallengeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewMfaChallengeInternalServerError creates a MfaChallengeInternalServerError with default headers values
func NewMfaChallengeInternalServerError() *MfaChallengeInternalServerError {
	return &MfaChallengeInternalServerError{}
}

/*
MfaChallengeInternalServerError describes a response with status code 500, with default header values.

internal server error
*/
type MfaChallengeInternalServerError struct {
}

// IsSuccess returns true when this mfa challenge internal server error response has a 2xx status code
func (o *MfaChallengeInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this mfa challenge internal server error response has a 3xx status code
func (o *MfaChallengeInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this mfa challenge internal server error response has a 4xx status code
func (o *MfaChallengeInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this mfa challenge internal server error response has a 5xx status code
func (o *MfaChallengeInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this mfa challenge internal server error response a status code equal to that given
func (o *MfaChallengeInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the mfa challenge internal server error response
func (o *MfaChallengeInternalServerError) Code() int {
	return 500
}

func (o *MfaChallengeInternalServerError) Error() string {
	return fmt.Sprintf("[POST /mfa/challenge][%d] mfaChallengeInternalServerError", 500)
}

func (o *MfaChallengeInternalServerError) String() string {
	return fmt.Sprintf("[POST /mfa/challenge][%d] mfaChallengeInternalServerError", 500)
}

func (o *MfaChallengeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
MfaChallengeBody mfa challenge body
swagger:model MfaChallengeBody
*/
type MfaChallengeBody struct {

	// code
	Code string `json:"code,omitempty"`
}

// Validate validates this mfa challenge body
func (o *MfaChallengeBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this mfa challenge body based on context it is used
func (o *MfaChallengeBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *MfaChallengeBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *MfaChallengeBody) UnmarshalBinary(b []byte) error {
	var res MfaChallengeBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
MfaChallengeOKBody mfa challenge o k body
swagger:model MfaChallengeOKBody
*/
type MfaChallengeOKBody struct {

	// challenge token
	ChallengeToken string `json:"challengeToken,omitempty"`

	// expires at
	// Format: date-time
	ExpiresAt strfmt.DateTime `json:"expiresAt,omitempty"`
}

// Validate validates this mfa challenge o k body
func (o *MfaChallengeOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateExpiresAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *MfaChallengeOKBody) validateExpiresAt(formats strfmt.Registry) error {
	if swag.IsZero(o.ExpiresAt) { // not required
		return nil
	}

	if err := validate.FormatOf("mfaChallengeOK"+"."+"expiresAt", "body", "date-time", o.ExpiresAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this mfa challenge o k body based on context it is used
func (o *MfaChallengeOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *MfaChallengeOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *MfaChallengeOKBody) UnmarshalBinary(b []byte) error {
	var res MfaChallengeOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
