// Code generated by go-swagger; DO NOT EDIT.

package metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/openziti/zrok/v2/rest_model_zrok"
)

// GetAccountDetailHandlerFunc turns a function with the right signature into a get account detail handler
type GetAccountDetailHandlerFunc func(GetAccountDetailParams, *rest_model_zrok.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAccountDetailHandlerFunc) Handle(params GetAccountDetailParams, principal *rest_model_zrok.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetAccountDetailHandler interface for that can handle valid get account detail params
type GetAccountDetailHandler interface {
	Handle(GetAccountDetailParams, *rest_model_zrok.Principal) middleware.Responder
}

// NewGetAccountDetail creates a new http.Handler for the get account detail operation
func NewGetAccountDetail(ctx *middleware.Context, handler GetAccountDetailHandler) *GetAccountDetail {
	return &GetAccountDetail{Context: ctx, Handler: handler}
}

/*
	GetAccountDetail swagger:route GET /detail/account metadata getAccountDetail

GetAccountDetail get account detail API
*/
type GetAccountDetail struct {
	Context *middleware.Context
	Handler GetAccountDetailHandler
}

func (o *GetAccountDetail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAccountDetailParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *rest_model_zrok.Principal
	if uprinc != nil {
		principal = uprinc.(*rest_model_zrok.Principal) // this is really a rest_model_zrok.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
