// Code generated by go-swagger; DO NOT EDIT.

package metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openziti/zrok/rest_model_zrok"
)

// GetAccountMetricsOKCode is the HTTP code returned for type GetAccountMetricsOK
const GetAccountMetricsOKCode int = 200

/*
GetAccountMetricsOK account metrics

swagger:response getAccountMetricsOK
*/
type GetAccountMetricsOK struct {

	/*
	  In: Body
	*/
	Payload *rest_model_zrok.Metrics `json:"body,omitempty"`
}

// NewGetAccountMetricsOK creates GetAccountMetricsOK with default headers values
func NewGetAccountMetricsOK() *GetAccountMetricsOK {

	return &GetAccountMetricsOK{}
}

// WithPayload adds the payload to the get account metrics o k response
func (o *GetAccountMetricsOK) WithPayload(payload *rest_model_zrok.Metrics) *GetAccountMetricsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get account metrics o k response
func (o *GetAccountMetricsOK) SetPayload(payload *rest_model_zrok.Metrics) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAccountMetricsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAccountMetricsBadRequestCode is the HTTP code returned for type GetAccountMetricsBadRequest
const GetAccountMetricsBadRequestCode int = 400

/*
GetAccountMetricsBadRequest bad request

swagger:response getAccountMetricsBadRequest
*/
type GetAccountMetricsBadRequest struct {
}

// NewGetAccountMetricsBadRequest creates GetAccountMetricsBadRequest with default headers values
func NewGetAccountMetricsBadRequest() *GetAccountMetricsBadRequest {

	return &GetAccountMetricsBadRequest{}
}

// WriteResponse to the client
func (o *GetAccountMetricsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetAccountMetricsInternalServerErrorCode is the HTTP code returned for type GetAccountMetricsInternalServerError
const GetAccountMetricsInternalServerErrorCode int = 500

/*
GetAccountMetricsInternalServerError internal server error

swagger:response getAccountMetricsInternalServerError
*/
type GetAccountMetricsInternalServerError struct {
}

// NewGetAccountMetricsInternalServerError creates GetAccountMetricsInternalServerError with default headers values
func NewGetAccountMetricsInternalServerError() *GetAccountMetricsInternalServerError {

	return &GetAccountMetricsInternalServerError{}
}

// WriteResponse to the client
func (o *GetAccountMetricsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
