// Code generated by go-swagger; DO NOT EDIT.

package metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openziti/zrok/rest_model_zrok"
)

// ListEnvironmentsOKCode is the HTTP code returned for type ListEnvironmentsOK
const ListEnvironmentsOKCode int = 200

/*
ListEnvironmentsOK list of environments

swagger:response listEnvironmentsOK
*/
type ListEnvironmentsOK struct {

	/*
	  In: Body
	*/
	Payload *rest_model_zrok.EnvironmentsList `json:"body,omitempty"`
}

// NewListEnvironmentsOK creates ListEnvironmentsOK with default headers values
func NewListEnvironmentsOK() *ListEnvironmentsOK {

	return &ListEnvironmentsOK{}
}

// WithPayload adds the payload to the list environments o k response
func (o *ListEnvironmentsOK) WithPayload(payload *rest_model_zrok.EnvironmentsList) *ListEnvironmentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list environments o k response
func (o *ListEnvironmentsOK) SetPayload(payload *rest_model_zrok.EnvironmentsList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEnvironmentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListEnvironmentsBadRequestCode is the HTTP code returned for type ListEnvironmentsBadRequest
const ListEnvironmentsBadRequestCode int = 400

/*
ListEnvironmentsBadRequest bad request (e.g., activityDuration exceeds 30d, invalid date format, invalid operator)

swagger:response listEnvironmentsBadRequest
*/
type ListEnvironmentsBadRequest struct {

	/*
	  In: Body
	*/
	Payload rest_model_zrok.ErrorMessage `json:"body,omitempty"`
}

// NewListEnvironmentsBadRequest creates ListEnvironmentsBadRequest with default headers values
func NewListEnvironmentsBadRequest() *ListEnvironmentsBadRequest {

	return &ListEnvironmentsBadRequest{}
}

// WithPayload adds the payload to the list environments bad request response
func (o *ListEnvironmentsBadRequest) WithPayload(payload rest_model_zrok.ErrorMessage) *ListEnvironmentsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list environments bad request response
func (o *ListEnvironmentsBadRequest) SetPayload(payload rest_model_zrok.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEnvironmentsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListEnvironmentsUnauthorizedCode is the HTTP code returned for type ListEnvironmentsUnauthorized
const ListEnvironmentsUnauthorizedCode int = 401

/*
ListEnvironmentsUnauthorized unauthorized

swagger:response listEnvironmentsUnauthorized
*/
type ListEnvironmentsUnauthorized struct {
}

// NewListEnvironmentsUnauthorized creates ListEnvironmentsUnauthorized with default headers values
func NewListEnvironmentsUnauthorized() *ListEnvironmentsUnauthorized {

	return &ListEnvironmentsUnauthorized{}
}

// WriteResponse to the client
func (o *ListEnvironmentsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// ListEnvironmentsInternalServerErrorCode is the HTTP code returned for type ListEnvironmentsInternalServerError
const ListEnvironmentsInternalServerErrorCode int = 500

/*
ListEnvironmentsInternalServerError internal server error

swagger:response listEnvironmentsInternalServerError
*/
type ListEnvironmentsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload rest_model_zrok.ErrorMessage `json:"body,omitempty"`
}

// NewListEnvironmentsInternalServerError creates ListEnvironmentsInternalServerError with default headers values
func NewListEnvironmentsInternalServerError() *ListEnvironmentsInternalServerError {

	return &ListEnvironmentsInternalServerError{}
}

// WithPayload adds the payload to the list environments internal server error response
func (o *ListEnvironmentsInternalServerError) WithPayload(payload rest_model_zrok.ErrorMessage) *ListEnvironmentsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list environments internal server error response
func (o *ListEnvironmentsInternalServerError) SetPayload(payload rest_model_zrok.ErrorMessage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEnvironmentsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
