// Code generated by go-swagger; DO NOT EDIT.

package metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ListMembersOKCode is the HTTP code returned for type ListMembersOK
const ListMembersOKCode int = 200

/*
ListMembersOK ok

swagger:response listMembersOK
*/
type ListMembersOK struct {

	/*
	  In: Body
	*/
	Payload *ListMembersOKBody `json:"body,omitempty"`
}

// NewListMembersOK creates ListMembersOK with default headers values
func NewListMembersOK() *ListMembersOK {

	return &ListMembersOK{}
}

// WithPayload adds the payload to the list members o k response
func (o *ListMembersOK) WithPayload(payload *ListMembersOKBody) *ListMembersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list members o k response
func (o *ListMembersOK) SetPayload(payload *ListMembersOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListMembersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListMembersNotFoundCode is the HTTP code returned for type ListMembersNotFound
const ListMembersNotFoundCode int = 404

/*
ListMembersNotFound not found

swagger:response listMembersNotFound
*/
type ListMembersNotFound struct {
}

// NewListMembersNotFound creates ListMembersNotFound with default headers values
func NewListMembersNotFound() *ListMembersNotFound {

	return &ListMembersNotFound{}
}

// WriteResponse to the client
func (o *ListMembersNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// ListMembersInternalServerErrorCode is the HTTP code returned for type ListMembersInternalServerError
const ListMembersInternalServerErrorCode int = 500

/*
ListMembersInternalServerError internal server error

swagger:response listMembersInternalServerError
*/
type ListMembersInternalServerError struct {
}

// NewListMembersInternalServerError creates ListMembersInternalServerError with default headers values
func NewListMembersInternalServerError() *ListMembersInternalServerError {

	return &ListMembersInternalServerError{}
}

// WriteResponse to the client
func (o *ListMembersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
