// Code generated by go-swagger; DO NOT EDIT.

package share

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/openziti/zrok/v2/rest_model_zrok"
)

// CreateShareNameHandlerFunc turns a function with the right signature into a create share name handler
type CreateShareNameHandlerFunc func(CreateShareNameParams, *rest_model_zrok.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateShareNameHandlerFunc) Handle(params CreateShareNameParams, principal *rest_model_zrok.Principal) middleware.Responder {
	return fn(params, principal)
}

// CreateShareNameHandler interface for that can handle valid create share name params
type CreateShareNameHandler interface {
	Handle(CreateShareNameParams, *rest_model_zrok.Principal) middleware.Responder
}

// NewCreateShareName creates a new http.Handler for the create share name operation
func NewCreateShareName(ctx *middleware.Context, handler CreateShareNameHandler) *CreateShareName {
	return &CreateShareName{Context: ctx, Handler: handler}
}

/*
	CreateShareName swagger:route POST /share/name share createShareName

CreateShareName create share name API
*/
type CreateShareName struct {
	Context *middleware.Context
	Handler CreateShareNameHandler
}

func (o *CreateShareName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateShareNameParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *rest_model_zrok.Principal
	if uprinc != nil {
		principal = uprinc.(*rest_model_zrok.Principal) // this is really a rest_model_zrok.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CreateShareNameBody create share name body
//
// swagger:model CreateShareNameBody
type CreateShareNameBody struct {

	// name
	Name string `json:"name,omitempty"`

	// namespace token
	NamespaceToken string `json:"namespaceToken,omitempty"`
}

// Validate validates this create share name body
func (o *CreateShareNameBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create share name body based on context it is used
func (o *CreateShareNameBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateShareNameBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateShareNameBody) UnmarshalBinary(b []byte) error {
	var res CreateShareNameBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
