// Code generated by go-swagger; DO NOT EDIT.

package share

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/openziti/zrok/rest_model_zrok"
)

// UpdateAccessHandlerFunc turns a function with the right signature into a update access handler
type UpdateAccessHandlerFunc func(UpdateAccessParams, *rest_model_zrok.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateAccessHandlerFunc) Handle(params UpdateAccessParams, principal *rest_model_zrok.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateAccessHandler interface for that can handle valid update access params
type UpdateAccessHandler interface {
	Handle(UpdateAccessParams, *rest_model_zrok.Principal) middleware.Responder
}

// NewUpdateAccess creates a new http.Handler for the update access operation
func NewUpdateAccess(ctx *middleware.Context, handler UpdateAccessHandler) *UpdateAccess {
	return &UpdateAccess{Context: ctx, Handler: handler}
}

/*
	UpdateAccess swagger:route PATCH /access share updateAccess

UpdateAccess update access API
*/
type UpdateAccess struct {
	Context *middleware.Context
	Handler UpdateAccessHandler
}

func (o *UpdateAccess) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateAccessParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *rest_model_zrok.Principal
	if uprinc != nil {
		principal = uprinc.(*rest_model_zrok.Principal) // this is really a rest_model_zrok.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// UpdateAccessBody update access body
//
// swagger:model UpdateAccessBody
type UpdateAccessBody struct {

	// bind address
	BindAddress string `json:"bindAddress,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// frontend token
	FrontendToken string `json:"frontendToken,omitempty"`
}

// Validate validates this update access body
func (o *UpdateAccessBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update access body based on context it is used
func (o *UpdateAccessBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateAccessBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateAccessBody) UnmarshalBinary(b []byte) error {
	var res UpdateAccessBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
