// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteOrganizationOKCode is the HTTP code returned for type DeleteOrganizationOK
const DeleteOrganizationOKCode int = 200

/*
DeleteOrganizationOK organization deleted

swagger:response deleteOrganizationOK
*/
type DeleteOrganizationOK struct {
}

// NewDeleteOrganizationOK creates DeleteOrganizationOK with default headers values
func NewDeleteOrganizationOK() *DeleteOrganizationOK {

	return &DeleteOrganizationOK{}
}

// WriteResponse to the client
func (o *DeleteOrganizationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteOrganizationUnauthorizedCode is the HTTP code returned for type DeleteOrganizationUnauthorized
const DeleteOrganizationUnauthorizedCode int = 401

/*
DeleteOrganizationUnauthorized unauthorized

swagger:response deleteOrganizationUnauthorized
*/
type DeleteOrganizationUnauthorized struct {
}

// NewDeleteOrganizationUnauthorized creates DeleteOrganizationUnauthorized with default headers values
func NewDeleteOrganizationUnauthorized() *DeleteOrganizationUnauthorized {

	return &DeleteOrganizationUnauthorized{}
}

// WriteResponse to the client
func (o *DeleteOrganizationUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// DeleteOrganizationNotFoundCode is the HTTP code returned for type DeleteOrganizationNotFound
const DeleteOrganizationNotFoundCode int = 404

/*
DeleteOrganizationNotFound organization not found

swagger:response deleteOrganizationNotFound
*/
type DeleteOrganizationNotFound struct {
}

// NewDeleteOrganizationNotFound creates DeleteOrganizationNotFound with default headers values
func NewDeleteOrganizationNotFound() *DeleteOrganizationNotFound {

	return &DeleteOrganizationNotFound{}
}

// WriteResponse to the client
func (o *DeleteOrganizationNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteOrganizationInternalServerErrorCode is the HTTP code returned for type DeleteOrganizationInternalServerError
const DeleteOrganizationInternalServerErrorCode int = 500

/*
DeleteOrganizationInternalServerError internal server error

swagger:response deleteOrganizationInternalServerError
*/
type DeleteOrganizationInternalServerError struct {
}

// NewDeleteOrganizationInternalServerError creates DeleteOrganizationInternalServerError with default headers values
func NewDeleteOrganizationInternalServerError() *DeleteOrganizationInternalServerError {

	return &DeleteOrganizationInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteOrganizationInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
