// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/openziti/zrok/rest_model_zrok"
)

// RemoveOrganizationMemberHandlerFunc turns a function with the right signature into a remove organization member handler
type RemoveOrganizationMemberHandlerFunc func(RemoveOrganizationMemberParams, *rest_model_zrok.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn RemoveOrganizationMemberHandlerFunc) Handle(params RemoveOrganizationMemberParams, principal *rest_model_zrok.Principal) middleware.Responder {
	return fn(params, principal)
}

// RemoveOrganizationMemberHandler interface for that can handle valid remove organization member params
type RemoveOrganizationMemberHandler interface {
	Handle(RemoveOrganizationMemberParams, *rest_model_zrok.Principal) middleware.Responder
}

// NewRemoveOrganizationMember creates a new http.Handler for the remove organization member operation
func NewRemoveOrganizationMember(ctx *middleware.Context, handler RemoveOrganizationMemberHandler) *RemoveOrganizationMember {
	return &RemoveOrganizationMember{Context: ctx, Handler: handler}
}

/*
	RemoveOrganizationMember swagger:route POST /organization/remove admin removeOrganizationMember

RemoveOrganizationMember remove organization member API
*/
type RemoveOrganizationMember struct {
	Context *middleware.Context
	Handler RemoveOrganizationMemberHandler
}

func (o *RemoveOrganizationMember) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewRemoveOrganizationMemberParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *rest_model_zrok.Principal
	if uprinc != nil {
		principal = uprinc.(*rest_model_zrok.Principal) // this is really a rest_model_zrok.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// RemoveOrganizationMemberBody remove organization member body
//
// swagger:model RemoveOrganizationMemberBody
type RemoveOrganizationMemberBody struct {

	// email
	Email string `json:"email,omitempty"`

	// organization token
	OrganizationToken string `json:"organizationToken,omitempty"`
}

// Validate validates this remove organization member body
func (o *RemoveOrganizationMemberBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this remove organization member body based on context it is used
func (o *RemoveOrganizationMemberBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *RemoveOrganizationMemberBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RemoveOrganizationMemberBody) UnmarshalBinary(b []byte) error {
	var res RemoveOrganizationMemberBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
