// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RemoveNamespaceGrantOKCode is the HTTP code returned for type RemoveNamespaceGrantOK
const RemoveNamespaceGrantOKCode int = 200

/*
RemoveNamespaceGrantOK namespace grant removed

swagger:response removeNamespaceGrantOK
*/
type RemoveNamespaceGrantOK struct {
}

// NewRemoveNamespaceGrantOK creates RemoveNamespaceGrantOK with default headers values
func NewRemoveNamespaceGrantOK() *RemoveNamespaceGrantOK {

	return &RemoveNamespaceGrantOK{}
}

// WriteResponse to the client
func (o *RemoveNamespaceGrantOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// RemoveNamespaceGrantUnauthorizedCode is the HTTP code returned for type RemoveNamespaceGrantUnauthorized
const RemoveNamespaceGrantUnauthorizedCode int = 401

/*
RemoveNamespaceGrantUnauthorized unauthorized

swagger:response removeNamespaceGrantUnauthorized
*/
type RemoveNamespaceGrantUnauthorized struct {
}

// NewRemoveNamespaceGrantUnauthorized creates RemoveNamespaceGrantUnauthorized with default headers values
func NewRemoveNamespaceGrantUnauthorized() *RemoveNamespaceGrantUnauthorized {

	return &RemoveNamespaceGrantUnauthorized{}
}

// WriteResponse to the client
func (o *RemoveNamespaceGrantUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// RemoveNamespaceGrantNotFoundCode is the HTTP code returned for type RemoveNamespaceGrantNotFound
const RemoveNamespaceGrantNotFoundCode int = 404

/*
RemoveNamespaceGrantNotFound not found

swagger:response removeNamespaceGrantNotFound
*/
type RemoveNamespaceGrantNotFound struct {
}

// NewRemoveNamespaceGrantNotFound creates RemoveNamespaceGrantNotFound with default headers values
func NewRemoveNamespaceGrantNotFound() *RemoveNamespaceGrantNotFound {

	return &RemoveNamespaceGrantNotFound{}
}

// WriteResponse to the client
func (o *RemoveNamespaceGrantNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// RemoveNamespaceGrantInternalServerErrorCode is the HTTP code returned for type RemoveNamespaceGrantInternalServerError
const RemoveNamespaceGrantInternalServerErrorCode int = 500

/*
RemoveNamespaceGrantInternalServerError internal server error

swagger:response removeNamespaceGrantInternalServerError
*/
type RemoveNamespaceGrantInternalServerError struct {
}

// NewRemoveNamespaceGrantInternalServerError creates RemoveNamespaceGrantInternalServerError with default headers values
func NewRemoveNamespaceGrantInternalServerError() *RemoveNamespaceGrantInternalServerError {

	return &RemoveNamespaceGrantInternalServerError{}
}

// WriteResponse to the client
func (o *RemoveNamespaceGrantInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
