// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/openziti/zrok/v2/rest_model_zrok"
)

// UpdateAccountPasswordHandlerFunc turns a function with the right signature into a update account password handler
type UpdateAccountPasswordHandlerFunc func(UpdateAccountPasswordParams, *rest_model_zrok.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateAccountPasswordHandlerFunc) Handle(params UpdateAccountPasswordParams, principal *rest_model_zrok.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateAccountPasswordHandler interface for that can handle valid update account password params
type UpdateAccountPasswordHandler interface {
	Handle(UpdateAccountPasswordParams, *rest_model_zrok.Principal) middleware.Responder
}

// NewUpdateAccountPassword creates a new http.Handler for the update account password operation
func NewUpdateAccountPassword(ctx *middleware.Context, handler UpdateAccountPasswordHandler) *UpdateAccountPassword {
	return &UpdateAccountPassword{Context: ctx, Handler: handler}
}

/*
	UpdateAccountPassword swagger:route PATCH /account admin updateAccountPassword

UpdateAccountPassword update account password API
*/
type UpdateAccountPassword struct {
	Context *middleware.Context
	Handler UpdateAccountPasswordHandler
}

func (o *UpdateAccountPassword) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateAccountPasswordParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *rest_model_zrok.Principal
	if uprinc != nil {
		principal = uprinc.(*rest_model_zrok.Principal) // this is really a rest_model_zrok.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// UpdateAccountPasswordBody update account password body
//
// swagger:model UpdateAccountPasswordBody
type UpdateAccountPasswordBody struct {

	// email
	Email string `json:"email,omitempty"`

	// password
	Password string `json:"password,omitempty"`
}

// Validate validates this update account password body
func (o *UpdateAccountPasswordBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update account password body based on context it is used
func (o *UpdateAccountPasswordBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateAccountPasswordBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateAccountPasswordBody) UnmarshalBinary(b []byte) error {
	var res UpdateAccountPasswordBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
