// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ResetPasswordRequestCreatedCode is the HTTP code returned for type ResetPasswordRequestCreated
const ResetPasswordRequestCreatedCode int = 201

/*
ResetPasswordRequestCreated reset password request created

swagger:response resetPasswordRequestCreated
*/
type ResetPasswordRequestCreated struct {
}

// NewResetPasswordRequestCreated creates ResetPasswordRequestCreated with default headers values
func NewResetPasswordRequestCreated() *ResetPasswordRequestCreated {

	return &ResetPasswordRequestCreated{}
}

// WriteResponse to the client
func (o *ResetPasswordRequestCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// ResetPasswordRequestBadRequestCode is the HTTP code returned for type ResetPasswordRequestBadRequest
const ResetPasswordRequestBadRequestCode int = 400

/*
ResetPasswordRequestBadRequest reset password request not created

swagger:response resetPasswordRequestBadRequest
*/
type ResetPasswordRequestBadRequest struct {
}

// NewResetPasswordRequestBadRequest creates ResetPasswordRequestBadRequest with default headers values
func NewResetPasswordRequestBadRequest() *ResetPasswordRequestBadRequest {

	return &ResetPasswordRequestBadRequest{}
}

// WriteResponse to the client
func (o *ResetPasswordRequestBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// ResetPasswordRequestInternalServerErrorCode is the HTTP code returned for type ResetPasswordRequestInternalServerError
const ResetPasswordRequestInternalServerErrorCode int = 500

/*
ResetPasswordRequestInternalServerError internal server error

swagger:response resetPasswordRequestInternalServerError
*/
type ResetPasswordRequestInternalServerError struct {
}

// NewResetPasswordRequestInternalServerError creates ResetPasswordRequestInternalServerError with default headers values
func NewResetPasswordRequestInternalServerError() *ResetPasswordRequestInternalServerError {

	return &ResetPasswordRequestInternalServerError{}
}

// WriteResponse to the client
func (o *ResetPasswordRequestInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
