/**
 * zrok
 * zrok client access
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Environment } from './environment';
import { Frontend } from './frontend';
import { Share } from './share';

export class EnvironmentAndResources {
    'environment'?: Environment;
    'frontends'?: Array<Frontend>;
    'shares'?: Array<Share>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "environment",
            "baseName": "environment",
            "type": "Environment"
        },
        {
            "name": "frontends",
            "baseName": "frontends",
            "type": "Array<Frontend>"
        },
        {
            "name": "shares",
            "baseName": "shares",
            "type": "Array<Share>"
        }    ];

    static getAttributeTypeMap() {
        return EnvironmentAndResources.attributeTypeMap;
    }
}

